### PR TITLE
V5 Appliance Cluster Example

### PR DESCRIPTION
**Pull request by jvanderhoof**
This PR provides instructions and code for deploying a small HA cluster using the Conjur V5 appliance. 

@jodyhuntatx, @infamousjoeg - not sure who runs this project, but mind taking a look?

### CODE REVIEW

**Comment by dataplex** [comment]
CDemo was designed to be run offline - can we change the scripts and the README to include information on getting the v5 appliance tar file and using the config file method used in the rest of CDemo to enable v5 instances?

**Comment by dataplex** [comment]
We also have a Dev branch that this should be merged into instead of master. We decided not to have merges into master directly. Merges to master should come from the Dev branch.

**Comment by jvanderhoof** [comment]
@dataplex,

We'll have an S3 bucket for retrieving images (images are tar files).  I'll update the instructions for retrieving from S3 when we generate the new image later today.

As V5 functionality is going to come over in in a steady stream, I don't want SEs trying to run the demo in with V5 until that functionality has been completed.  That's why I put v5 work into it's own namespace.

**Comment by jodyhuntatx** [comment]
I submit we can delete this branch if the v5-merge branch passes muster and is merged in to the Dev branch.

**Pull request closed without merging**
