### PR TITLE
Adds (optional) Vagrantfile

### PR DESCRIPTION
**Pull request by ryanprior**
The Vagrantfile follows the instructions and specifications set out in the
README, allowing the operator to get up and running quickly if they already have
Vagrant and VirtualBox installed.

### CODE REVIEW

**Review by CaptainFluffyToes — CHANGES_REQUESTED** [review]
Does cdemo need to be cloned into /opt in order for this to work correctly?

**Comment by ryanprior** [comment]
It doesn't have to be `/opt/cdemo`, it could be anywhere. Do you have a preferred location where the files should be mounted?

**Comment by CaptainFluffyToes** [comment]
It looked like the vargrant file is looking for a specific directory to run installansible (https://github.com/conjurdemos/cdemo/pull/52/files/74fa0935729452528a25004a48595b44bd9758fc#diff-23b6f443c01ea2efcb4f36eedfea9089R15) 
Is there any way to account for that in case the directory is cloned elsewhere?  We could keep this as a "hidden" feature for sure if that's it's main purpose.

**Comment by ryanprior** [comment]
@CaptainFluffyToes this line specifies that the directory should be mounted at that particular location: https://github.com/conjurdemos/cdemo/pull/52/files/74fa0935729452528a25004a48595b44bd9758fc#diff-23b6f443c01ea2efcb4f36eedfea9089R13

This should ensure the files can be found at the proper location within the VM, wherever the directory may be cloned on the host.

**Review by CaptainFluffyToes — APPROVED** [review]

**Pull request merged**
